### ISSUE TITLE
Compiling Error: Symbol's value as variable is void: imenu-list-buffer-name 

### ISSUE THREAD

**Issue by xuchunyang** [bmag/imenu-list#12]
Try to install from melpa with package.el, but compiling failed with the following log:

```
Leaving directory `/Users/xcy/.emacs.d/elpa/imenu-list-20150626.417' 
^L
Compiling file /Users/xcy/.emacs.d/elpa/imenu-list-20150626.417/imenu-list.el at Sun Jun 28 09:36:37 2015
Entering directory `/Users/xcy/.emacs.d/elpa/imenu-list-20150626.417/'
imenu-list.el:343:1:Error: Symbol's value as variable is void: imenu-list-buffer-name 
^L
Compiling no file at Sun Jun 28 09:36:38 2015
```

there is no `*.elc` files as well:

``` sh
~/.emacs.d/elpa/imenu-list-20150626.417 $ ls
imenu-list-autoloads.el  imenu-list-pkg.el  imenu-list.el
```

The compiling error only occurs only in the first time, so if you want to reproduce this issue, delete imenu-list (e.g., don't require it), restart Emacs and install from melpa (or use `package-install-from-buffer`).

PS. imenu-list itself works fine.

**Comment by bmag** [comment]
Thanks, I'm gonna look into this tomorrow or the day after.

**Comment by bmag** [comment]
Apparently `rx` is evaluated at compilation time, and `imenu-list-buffer-name` wasn't available at compilation time. I've replaced it with `regexp-quote`, which is evaluated at run time. Should be fixed now.

**Comment by xuchunyang** [comment]
The compiling error is solved. Thanks for the fix and explanation. 

While upgrading to latest imenu-list from melpa, I noticed some compiling warnings:

```
Compiling file /Users/xcy/.emacs.d/elpa/imenu-list-20150629.530/imenu-list.el at Mon Jun 29 22:42:00 2015
Entering directory `/Users/xcy/.emacs.d/elpa/imenu-list-20150629.530/'

In imenu-list-install-purpose-display:
imenu-list.el:363:15:Warning: reference to free variable
    `purpose-special-action-sequences'
imenu-list.el:363:15:Warning: assignment to free variable
    `purpose-special-action-sequences'

In end of data:
imenu-list.el:504:1:Warning: the function `hs-toggle-hiding' is not known to
    be defined.
```

Not sure if you care about them.

**Comment by bmag** [comment]
These warning don't cause any errors at run time, so I'm fine with leaving them as is.

The first two warnings are false positives. They are wrapped in an `eval-after-load` that ensures that `purpose-special-action-sequences` is defined properly at run time.

The third warning I think is also a false positive. `hs-toggle-hiding` is part of `hideshow`, which I'm almost certain is auto-loaded when `hs-minor-mode` is called.
