### ISSUE TITLE
Problem in Evil mode

### ISSUE THREAD

**Issue by QiangF** [bmag/imenu-list#13]
Hi everyone,
I want to disable evil-mode for imenu list. The function I am using is

(evil-set-initial-state MODE STATE)
Set the initial state for MODE to STATE.
This is the state the buffer comes up in.

what is the mode for imenu list? I tried imenu-list-mode and imenu-list-minor-mode, all doesn't work.

Also how I move the point to imenu-list window after the command imenu-list-minor-mode? I think most user would like to focus on that buffer if they run that command.

Thank you for your help!

**Comment by bmag** [comment]
> what is the mode for imenu list?

I think you're looking for `imenu-list-major-mode`. Did you not find it with `describe-function` (<kbd>C-h f</kbd>)?

> Also how I move the point to imenu-list window after the command imenu-list-minor-mode?

I will add later this week a user option to decide if `imenu-list-minor-mode` should focus imenu-list's window. In the meantime, you can use this code snippet:

``` elisp
(add-hook 'imenu-list-minor-mode-hook
          (lambda () (when imenu-list-minor-mode (imenu-list-show))))
```

> I think most user would like to focus on that buffer if they run that command.

I'm not so sure. Another use-case is leaving the imenu-list open on the side while working on other bufferss. Imenu-list should "follow" you - update itself according to the current buffer. It would have been nice to really know which use-case is more popular, though.

**Comment by QiangF** [comment]
Your solution works perfectly. Thank you!

**Comment by bmag** [comment]
Added a new variable `imenu-list-focus-after-activation`. You can replace the code snippet above with the following:

``` elisp
(setq imenu-list-focus-after-activation t)
```
