### ISSUE TITLE
imenu-list causes `emacs --daemon` to hang.

### ISSUE THREAD

**Issue by egh** [bmag/imenu-list#14]
If imenu-list is installed, the following `~/.emacs.d/init.el` file will cause `emacs --daemon` to hang:

```
(add-hook 'prog-mode-hook #'imenu-list-minor-mode)
```

```
λ emacs --daemon

Warning: due to a long standing Gtk+ bug
http://bugzilla.gnome.org/show_bug.cgi?id=85715
Emacs might crash when run in daemon mode and the X11 connection is unexpectedly lost.
Using an Emacs configured with --with-x-toolkit=lucid does not have this problem.
[ never returns ]
```

```
λ emacs --version
GNU Emacs 25.0.50.2
```

**Comment by bmag** [comment]
Thanks for reporting. It sounds like a weird bug, I'll check it later today. Does this also happen on emacs 24.5?

**Comment by bmag** [comment]
Should work now. You'll still get a message about an error, but it won't prevent emacs from starting as expected. The fixed version should be available soon in MELPA.

Please note that the following `init.el` file will also cause the same problem:

``` elisp
(add-hook 'prog-mode-hook (lambda () (error "Whoops")))
```

My guess is that `prog-mode-hook` is called when emacs creates the `*scratch*` buffer, and that `emacs --daemon` doesn't handle errors properly in that case. In our case, `imenu` couldn't create an index for the `*scratch*` buffer and threw an error. I changed `imenu-list-update` to catch these indexing errors, so it should be fine now.

**Comment by egh** [comment]
Thank you for the quick response! Works great.
