### ISSUE TITLE
imenu-list fails on dired+.el

### ISSUE THREAD

**Issue by QiangF** [bmag/imenu-list#16]
Hello Sir,
I am using imenu-list version 0.4 in emacs 24.4. I have a customized imenu section to organize files,  with this format
      (add-to-list 'imenu-generic-expression `("Sections"
      ,(concat (regexp-quote comment-start) " \* \(.+\)$") 1))
For elisp mode, the corresponding imenu-generic-expression for my section is
      ("Sections" "; \* \(.+\)$" 1).
It works well in imenu, but imenu-list also put all the comments (line start with ;) under my section. 
There must be something wrong in the parsing of customised imenu sections. 
I also has this in my setup
  (setq imenu-prev-index-position-function nil)
Thank you for your help!

**Comment by bmag** [comment]
Thank you for the report, this sounds interesting.
There was a slight mistake in your report, I had to use this code to reproduce the bug:

``` elisp
;; note the two double backslashes in the regexp (you had two single backslashes)
(add-to-list 'imenu-generic-expression `("Sections" ,(concat (regexp-quote comment-start) " * \\(.+\\)$") 1))
(setq imenu-previ-index-position-function nil)
```

In imenu-list, I see that imenu-list puts all the comments under the "Sections" category.
However, when using imenu, I see that also imenu puts all of the comments under the "Sections" category. It looks to me like the bug isn't in imenu-list, but in the configuration of imenu.

Can you please:
- 1) provide a simple elisp file that we can both test (I used dired+.el, but it's very big)
- 2) with the elisp buffer as the current buffer, please provide the values of these variables:
  - 1. imenu-generic-expression
  - 2. imenu-prev-index-position
  - 3. imenu--index-alist
  - 4. imenu-list--imenu-entries
  
  To see the value of the variable, use `C-h k <variable name> RET`. The first three variables are buffer-local, so it's important to put the focus on the elisp buffer before using `C-h k`. `imenu--index-alist` and `imenu-list--imenu-entries` should be equal.
- 3) what are the contents of imenu-list buffer, and what contents do you expect it to have?

**Comment by QiangF** [comment]
Thank you Sir. It's a fault in my setting. The \* needs to be escaped. I add a star in my heading to differentiate it from other headings in outline mode,  and my heading has higher level, so I can organise the files into sections. When I add to double slash to the generic expression of my section (heading), all work as expected. I can see those sections in imenu-list and jump to it using helm imenu. I am closing this issue.
Here is my setup for outline-mode if you are interested, the number of displayed backslash could be wrong.

```
(defun my/heading()
"custom heading for all prog mode, heading must ends in
outline-heading-end-regexp,which is : for python mode
* in heading to differentiate from comment, custom heading has higher level than other headings"
(when  (and (not (equal major-mode 'org-mode)) comment-start)
(make-local-variable 'my/outline-regexp)
(make-local-variable 'my-outline-max-level)
(setq my-outline-max-level 8)
(setq my/outline-regexp (concat (regexp-quote comment-start) " [*]\\{1,8\\}"))
(setq outline-heading-alist '()) ;; make outline promote work
(let ((level 0)
    (level-prefix (concat comment-start " ")))
    (while (< level my-outline-max-level)
    (setq outline-heading-alist (cons (cons level-prefix level) outline-heading-alist)
            level (1+ level)
            level-prefix (concat level-prefix "*")))
    (setq outline-heading-alist (nreverse outline-heading-alist)))
(setq outline-regexp (concat my/outline-regexp "\\|" outline-regexp)
    outline-level (lambda()
    (let* ((data (match-data))
    (start (car data))
    (end (cadr data))
    (level (- end start)))
    (if (looking-at my/outline-regexp)
        (- level 2) ;; subtract two spaces
        (+ level my-outline-max-level));; 8 is the maximum custom heading levels
    )))))
(add-hook 'prog-mode-hook #'outline-minor-mode)
(add-hook 'text-mode-hook #'outline-minor-mode)
(add-hook 'outline-minor-mode-hook 'my/heading)
```

**Comment by bmag** [comment]
That's a really nifty trick, thanks for sharing :smile:
