### ISSUE TITLE
Default action for TAB

### ISSUE THREAD

**Issue by StreakyCobra** [bmag/imenu-list#19]
When trying `imenu-list` for the first time, I intuitively expected `TAB` to fold/unfold the sections, as it is done for instance in `org-mode`.

I think `n` and `p` are enough to navigate up/down in the list, hence using `TAB` for folding/unfolding (`f` can be kept anyway).

As this is more a personal preference than an objective observation, just close this issue if you don't like it :-)

**Comment by bmag** [comment]
I've change the binding, since I argee that it's more intuitive this way. `tab` now folds/unfolds, and `backtab` is not bound.

**Comment by StreakyCobra** [comment]
:+1: many thanks!
