### ISSUE TITLE
Allow manual update of *Ilist* buffer

### ISSUE THREAD

**Issue by colinxy** [bmag/imenu-list#26]
Hi, I really like this package so far, but I really want some dired like keybindings inside the `*Ilist*` buffer. This includes `g`, which refresh the `*Ilist*` buffer manually, and `q`, which buries the buffer.

It would be really nice to have these features, thanks!

**Comment by colinxy** [comment]
I have attempted at adding these features at configuration level, but it looks so awkward to make a function interactive manually.

```emacs lisp
(with-eval-after-load 'imenu-list
  (define-key imenu-list-major-mode-map (kbd "q") 'imenu-list-minor-mode)
  (define-key imenu-list-major-mode-map (kbd "g")
    (lambda () (interactive) (imenu-list-insert-entries))))
```

**Comment by bmag** [comment]
First of all, thanks for the input.

> This includes `g`, which refresh the `*Ilist*` buffer manually

If you use the command `imenu-list-minor-mode` to toggle imenu-list on and off, then `*Ilist*` buffer is updated automatically according to the current buffer everytime the user is idle for at least 1 second.
Furthermore, `imenu-list-insert-entries` only redraws the `*Ilist*` buffer, it doesn't update any changes that were made to the indexed buffer. Does your `g` shortcut really updates anything? Could you describe your workflow and why you want/need this new shortcut? I'm not saying I'm against it, I'm just trying to understand the use-case.

> and `q`, which buries the buffer

By default, `q` is bound to `quit-window`, which already closes the window (or shows previous buffer that was displayed in the window) and buries the buffer. Regardless, rebinding `q` as you did is perfectly reasonable for users who use `imenu-list-minor-mode` to toggle imenu-list on/off.

**Comment by bmag** [comment]
I wrote a new command `imenu-list-quit-window` and bound it to `q` by default. It combines `quit-window` and `imenu-list-minor-mode` and should be better than binding `imenu-list-minor-mode`.

I also wrote `imenu-list-refresh` and bound it to `g`. I don't know if it fits your workflow, though. Can you please try out the changes in #27 and tell me what you think?

**Comment by colinxy** [comment]
Thanks for the quick reply. Let me explain my use cases.

For `q`, when I am currently in the `*Ilist*` buffer, I naturally hit `q` to quit the buffer. Then I will have to do `imenu-list-minor-mode` twice to reopen `imenu-list`, because the first `imenu-list-minor-mode` tells me to disables it, and the second to enable it.

I think this could potentially fixed by `imenu-list-minor-mode` checking whether the buffer is visible, and just show it rather than disable it when called.

For `g`, it is needed when I accidentally kill the `*Ilist*` buffer, which happens a lot to me. Then I have to do `imenu-list-minor-mode` twice to reenable it, but end up finding the `*Ilist*` buffer empty. Also there are cases when auto-refreshing is lagging a bit. Thus I want to be able to refresh the buffer manually.

I will try out your newest commit as soon as possible.

**Comment by bmag** [comment]
Thanks for the feedback. I've updated the PR (see https://github.com/bmag/imenu-list/pull/27#issuecomment-279737040) and I think it fixes all those issues now.

**Comment by bmag** [comment]
Fixed in master (see https://github.com/bmag/imenu-list/pull/27#issuecomment-279960836)
