### ISSUE TITLE
Org-entry  at the bottom? 

### ISSUE THREAD

**Issue by HomelandScenery** [bmag/imenu-list#31]
Hello author, I appreciate your work.
When I open a long org-mode document(http://doc.norang.ca/org-mode.org), Headline for the imenu-list is highlighted at the top, It's good, but when I browsing the org files, the headline highlight will be at the bottom, so that is not suited, is there a correct way to set up?
![list1](https://user-images.githubusercontent.com/19407813/28741663-003c045a-744e-11e7-98da-85ce910cf497.png)

![list2](https://user-images.githubusercontent.com/19407813/28741670-2452cc3e-744e-11e7-9419-5aa821f0a3ec.png)

**Comment by bmag** [comment]
I don't understand the issue. Do you mean that "How To Use This Document" doesn't have an underline, while "Tags" does have an underline, and you want "How To Use This Document" to have an underline as well?

**Comment by HomelandScenery** [comment]
No, It's not about the underline, I mean the posiotion of a Headline in Ilist buffer.
 "How To Use This Document" is at the top of Ilist buffer, but "Tags" is in the bottom,
How to fix it ?

**Comment by HomelandScenery** [comment]
Emacs version:  GNU Emacs 25.1.1 (x86_64-w64-mingw32) of 2016-09-22

**Comment by bmag** [comment]
You want the current entry to always be at the top?

**Comment by HomelandScenery** [comment]
> You want the current entry to always be at the top?

Yes! Top or Center, but no more bottom. Just like
`C-l runs the command recenter-top-bottom (found in global-map)`

**Comment by bmag** [comment]
These settings will keep the current entry at the top when `*Ilist*` buffer is scrolled:
```elisp
(add-hook 'imenu-list-major-mode-hook
  (lambda ()
    (setq-local scroll-conservatively 0)
    (setq-local scroll-down-aggressively 1)
    (setq-local scroll-up-aggressively 1)))
```

If you want the current entry in the middle, replace 1 with 0.5.

**Comment by HomelandScenery** [comment]
It's GREAT! Thanks!
```emacs-lisp
(use-package imenu-list
  :ensure t
  :bind (("<f8>" . imenu-list-smart-toggle))
  :config
  (setq imenu-list-auto-resize t
        imenu-list-focus-after-activation t
        imenu-list-size 0.2)
  :init
  (add-hook 'imenu-list-major-mode-hook
            (lambda ()
              (setq-local scroll-conservatively 0)
              (setq-local scroll-down-aggressively 0.618)
              (setq-local scroll-up-aggressively 0.618))))
```
