### ISSUE TITLE
Select window displaying *Ilist* buffer

### ISSUE THREAD

**Issue by priyadarshan** [bmag/imenu-list#32]
Hi,

Right now I am using a naive function to select the window displaying `*Ilist*` buffer:
```
(defun my-imenu-list-switch ()
      (interactive)
      (imenu-list-smart-toggle)
      (imenu-list-smart-toggle))
```
Is there a more proper way to select `imenu-list` window unconditionally (no matter if I am already in it or not)?

Thank you for `imenu-list`, it has been such a timesaver for my workflow!

**Comment by bmag** [comment]
If the `imenu-list` window already exists:
```elisp
(select-window (get-buffer-window imenu-list-buffer-name))
```

**Comment by priyadarshan** [comment]
Thank you, that is perfect.

I have wrapped it into a small defun into imenu-list `use-package` invocation:

```
(use-package imenu-list
    :ensure t
    :defer 4
    :bind (( "C-'" . imenu-list-smart-toggle)
	   ( "s-'" . my-imenu-list-window-select))
    :config
    (defun my-imenu-list-window-select ()
      (interactive)
      (select-window (get-buffer-window imenu-list-buffer-name)))
    (setf imenu-list-focus-after-activation t
	  imenu-list-size 20
	  imenu-list-position 'right)
    (imenu-list-minor-mode))
```

Thank you once again for imenu-list.

**Comment by bmag** [comment]
Glad I could help
