### ISSUE TITLE
Calling imenu-list in Ilist buffer should quit

### ISSUE THREAD

**Issue by rnkn** [bmag/imenu-list#36]
Currently calling `imenu-list` in the Ilist buffer signals an error, e.g. I have `imenu-list` bound to `M-s l` so I frequently press this once to open the Ilist buffer, then another absentmindedly thinking it will quit the buffer, but it gets the error. A nicer experience would be to call `imenu-list-quit-window`.

**Comment by bmag** [comment]
Thanks for the suggestion. I will probably implement it in the second half of February (you can ping me if I forget). Sorry for late response.

**Comment by rnkn** [comment]
Since you asked, *ping!* 🛎

**Comment by rnkn** [comment]
I actually created my own alternative to Imenu-list that uses a different approach, so if no one else wanted this feature you can safely close.
