### ISSUE TITLE
Feature Request: Clear menu

### ISSUE THREAD

**Issue by wyuenho** [bmag/imenu-list#37]
There doesn't appear to be any facilities to clear imenu-list, this sometimes leaves an imenu-list populated with the entries from the previous buffer while visiting a buffer that has no imenu index in purpose-x-code1.

**Comment by bmag** [comment]
There's no advantage to showing an empty imenu-list window, when switching from an indexed buffer to a buffer with no index. If we keep the previous buffer's index, at least it can be used for navigation to a specific entry in the original buffer.

It's possible to implement an `imenu-list-clear` function, but is it really necessary?

P.S. sorry for late response

**Comment by wyuenho** [comment]
I think it's necessary. imenu's API is weird but at least it all will clear it's own menu when visiting a buffer that has no index. In xcode1 for example, when looking at 2 files with index, imenu-list changes, but when looking at a file that doesn't, imenu-list doesn't update. This is inconsistent and violates the pattern established by the bahavior for files that have indices.

**Comment by bmag** [comment]
You say it is inconsistent, but it is still pretty obvious which buffer is indexed in imenu-list, so it is not confusing. Thus, I do not regard it as a problem.

I'm sorry that you had to wait a whole month just for this short answer, I'm sure it's frustrating, but I was just very busy and couldn't help it :frowning_face:

**Comment by wyuenho** [comment]
The point is not whether it's obvious which buffer the menu belong to, but whether the existence of the menu itself makes sense. The inability to clear the menu gives the impression that the last buffer is still in focus, which it is not. It's simply a UI issue, Emacs is already full of terrible UI conventions, please don't make it worse.

**Comment by bmag** [comment]
Well, I believe the existence of the menu makes sense, so I'm not going to change the current behavior. I am willing to accept a PR that adds an opt-in feature of clearing the index automatically.
