### ISSUE TITLE
Consider using display-buffer-in-side-window

### ISSUE THREAD

**Issue by rnkn** [bmag/imenu-list#39]
The function `display-buffer-in-side-window` puts windows neatly in side windows using the same alist format you're using for `imenu-list-display-buffer` but without the need for the complex frame/window management.

I'm pretty sure you could also then drop the `cl-lib` dependency too.

**Comment by rnkn** [comment]
p.s. Here's an implementation example: https://github.com/rnkn/side-notes/blob/master/side-notes.el

**Comment by dsedivec** [comment]
I wrote [this](https://github.com/dsedivec/dot-emacs-d/blob/ddc3fec6a2a884ce4adf730a2eb255dab97834b7/recipes/imenu-list-in-side-buffer.el) to display imenu-list in a dedicated side window with preserved size.  I've been using this for what seems like months and it's been behaving as I'd expect.  Feel free to copy any or all of that code as you'd like.  I could eventually womp up a PR if that's requested.

**Comment by atanasj** [comment]
@dsedivec, I'd like to try this but not sure how to implement it. I'm looking for something that will preserver the width of `imenu-list` when `golden-ratio` is activated. Do you think this will work? Or better yet, could you please let me know how to use your script?

**Comment by dsedivec** [comment]
> @dsedivec, I'd like to try this but not sure how to implement it. I'm looking for something that will preserver the width of `imenu-list` when `golden-ratio` is activated. Do you think this will work? Or better yet, could you please let me know how to use your script?

To use my script you can probably just save it under somewhere such as `~/.emacs.d` then `(load "path/to/the/script")` and that should be all you need.  If you were already displaying imenu-list then you may need to quit and re-display it.

I cannot say whether or not golden-ratio will leave the dedicated side window alone.

**Comment by rnkn** [comment]
If you're interested, I've written an alternate approach to navigating imenu in a side-window that use `display-buffer-in-side-window`: https://github.com/rnkn/side-hustle

This works for my needs so I'll close this issue.
