### ISSUE TITLE
Emacs 27 window--display-buffer signature changed

### ISSUE THREAD

**Issue by dsedivec** [bmag/imenu-list#45]
Hot on the heels of https://github.com/bmag/emacs-purpose/issues/137, I'll point out that `imenu-list-display-buffer` has the same problem. :)

In this case, if I read [the Emacs commit message](https://github.com/emacs-mirror/emacs/commit/f646675cd163) right, perhaps we can just change `imenu-list-display-buffer` to set `dedicated` in the alist it passes in?

```elisp
(defun imenu-list-display-buffer (buffer alist)
  "Display the imenu-list buffer at the side.
This function should be used with `display-buffer-alist'.
See `display-buffer-alist' for a description of BUFFER and ALIST."
  (or (get-buffer-window buffer)
      (let ((window (ignore-errors (split-window (frame-root-window) (imenu-list-split-size) imenu-list-position))))
        (when window
          ;; Change here:
          (window--display-buffer buffer window 'window (cons (dedicated . t)
                                                              alist))
          window))))
```

Of course I have no idea if this will work in Emacs < 27.  (Actually I'm not sure I'd notice if this wasn't working right in Emacs == 27, either.)

Thank you for this excellent package!

**Comment by bmag** [comment]
Thanks, can you confirm the following patch fixes the issue and doesn't seem to break anything?
```diff
@@ -417,7 +417,11 @@ See `display-buffer-alist' for a description of BUFFER and ALIST."
   (or (get-buffer-window buffer)
       (let ((window (ignore-errors (split-window (frame-root-window) (imenu-list-split-size) imenu-list-position))))
         (when window
-          (window--display-buffer buffer window 'window alist t)
+          (window--display-buffer buffer window 'window alist)
+          (set-window-dedicated-p window t)
           window))))
 
 (defun imenu-list-install-display-buffer ()
```

**Comment by dsedivec** [comment]
> Thanks, can you confirm the following patch fixes the issue and doesn't seem to break anything?

Confirmed: fixes the problem here and doesn't immediately seem to break anything at all.

**Comment by bmag** [comment]
Thanks. Fixed by https://github.com/bmag/imenu-list/commit/46008738f8fef578a763c308cf6695e5b4d4aa77, should be available from Melpa soon.
