### ISSUE TITLE
Change window type from dedicated to specific

### ISSUE THREAD

**Issue by ahmednofal** [bmag/imenu-list#48]
Hello, thank you very much for this tool, I am a newbie to emacs coming from vim, might be using a specific window instead of a dedicated window a better fit? Because specific windows break lines automatically so resizing the imenu-list buffer won't have line disappearing at the right edge also specific windows can be switched to using SPC Num in spacemacs so that would be really helpful for users to switch focus back and forth from imenu without the need to toggle it on and off to switch the focus. Thank you very much again.

**Comment by bmag** [comment]
I'm sorry, but I can't understand the last sentence. Please explain what is the problem and what is your suggestion.

**Comment by bmag** [comment]
I'll re-open the issue if I hear back from you.
