### ISSUE TITLE
Automatically refresh when buffer is modified?

### ISSUE THREAD

**Issue by lvictorino** [bmag/imenu-list#50]
Hi, I'm looking for a way to have `imenu-list` automatically refreshed when the buffer is modified. I've read about `imenu-list-refresh` to perform that manually, but is there a way to do that automatically?
Thanks.

**Comment by bmag** [comment]
Yes, it is written in the first few paragraph of the README file. Use `imenu-list-minor-mode` or `imenu-list-start-toggle`.
