### ISSUE TITLE
How do I get a function to have a title?

### ISSUE THREAD

**Issue by e190** [bmag/imenu-list#57]
I want this effect:
![图片](https://user-images.githubusercontent.com/39932163/78877756-edf85200-7a83-11ea-9058-5f97ad1ce3b8.png)
But here's the thing:
![图片](https://user-images.githubusercontent.com/39932163/78877846-0bc5b700-7a84-11ea-8b3e-886173790cc7.png)

**Comment by bmag** [comment]
imenu-list displays the same tree structure the `imenu` command uses. You will need to configure `imenu` to achieve what you want (look for "imenu create index function" or something like that, and related variables). The configuration for `imenu` is usually done by the major-mode (in this case `emacs-lisp-mode`) or some minor modes (e.g. Semantic).
