### ISSUE TITLE
How could start imenu-list with a collapse mode of tree

### ISSUE THREAD

**Issue by AbstProcDo** [bmag/imenu-list#60]
The imenu-list displays expanded trees by default. Is it possible to open it in collapse mode?

**Comment by bmag** [comment]
imenu-list uses Hideshow (`hs-minor-mode`) for folding. Theoretically, hooking `hs-hide-all` or `hs-hide-level` into the correct place should work. However, you'll be affected by bug #7 which I don't know how to solve.

**Comment by AbstProcDo** [comment]
thank you.
