### ISSUE TITLE
Support for C+17 compact nested namespaces

### ISSUE THREAD

**Issue by fperies** [bmag/imenu-list#64]
Hello,

First, thank you for Imenu which is a neat minor mode !

Imenu doesn't seem to work as expected when nested namespaces are written using the compact syntax provided by C++17.
For instance, if the namespaces are written like the following, Imenu shows correctly variable foo:

```
namespace a {
namespace b {
char foo;
}
}
```

Now, if it is written with C++17 flavor, Imenu shows nothing:
```
namespace a::b {
char foo;
}

```
Would it be possible to fix this ?

Thanks!

**Comment by bmag** [comment]
imenu-list relies on an Emacs feature called "Imenu", and shows the same index that you can access via `M-x imenu` command. To fix this issue, you need to fix the Imenu configuration. This is usually handled by the buffer's major mode (e.g. `c++-mode`) or by a minor mode (e.g. `semantic-mode`, Eglot, `lsp-mode`).

What is your C++ configuration, what are the values of `imenu-create-index-function` and `imenu-generic-expression` in C++ buffers, and do you see any advices defined in the documentation provided by executing `C-h f imenu-default-create-index-function RET` in a C++ buffer?

**Comment by fperies** [comment]
Hello @bmag and thank you for your reply.

I'm using Spacemacs in C++//l mode.

`imenu-create-index-function` value is set to `imenu-default-create-index-function` which is defined from imenu.el.

`imenu-generic-expression`is set as follows:
`Value:
((nil "^\\<.*[^[:alnum:]_:<>~]\\(\\([[:alnum:]_:<>~]*::\\)?operator\\>[ 	]*\\(()\\|[^(]*\\)\\)[ 	]*([^)]*)[ 	]*[^ 	;]" 1)
 (nil "^\\([[:alpha:]_][[:alnum:]_:<>~]*\\)[ 	]*([ 	]*\\([^ 	(*][^)]*\\)?)[ 	]*[^ 	;(]" 1)
 (nil "^\\<[^()
]*[^[:alnum:]_:<>~]\\([[:alpha:]_][[:alnum:]_:<>~]*\\)\\([ 	
]\\|\\\\
\\)*(\\([ 	
]\\|\\\\
\\)*\\([^ 	
(*][^()]*\\(([^()]*)[^()]*\\)*\\)?)\\([ 	
]\\|\\\\
\\)*[^ 	
;(]" 1)
 ("Class" "^\\(template[ 	]*<[^>]+>[ 	]*\\)?\\(class\\|struct\\)[ 	]+\\([[:alnum:]_]+\\(<[^>]+>\\)?\\)\\([ 	
]\\|\\\\
\\)*[:{]" 3))`

Unfortunately, I see no particular recommendations when I evaluate function `imenu-default-create-index-function` in a C++ buffer: the cursor jumps to the first line of class definition and in the echo area I just see :
![image](https://user-images.githubusercontent.com/7024137/109656378-a596c680-7b64-11eb-83bf-578411816d3f.png)

All methods and data members inside the class definition are simply ignored by `imenu`!

**Comment by bmag** [comment]
I'm not certain, but I think you are using the built-in Emacs support for C++, so you should look into how to configure or add support for C++17.

Spacemacs should have a layer for LSP. If you enable it properly (might need `auto-completion` layer as well, or some such), then the language server (Clangd or CCLS) will provide imenu support. In this case, you will just need to configure the language server to use C++17 (might be supported out-of-the-box, even).

Once `M-x imenu` shows you the correct entries, then imenu-list will show them as well. I don't think there's anything more I can help with here, so I'm closing the issue.
