### ISSUE TITLE
ilist buffer does not load inside new window when calling up imenu-list

### ISSUE THREAD

**Issue by eldritchgreene** [bmag/imenu-list#66]
I'm having this strange issue with imenu-list, using emacs on Android via Termux, when I start imenu-list the side window opens with the same content of my current window and I get the following error:

Wrong number of arguments: (3 . 4), 5

The ilist buffer does load but separately. What could this be? Thanks.

**Comment by bmag** [comment]
Thanks for reporting.

Can you provide me with a backtrace? Before starting imenu-list, please enable debug-on-error (`M-x toggle-debug-on-error`). Now, starting imenu-list should display a backtrace buffer with the function calls that lead to the error. Paste the contents of the buffer here.

**Comment by eldritchgreene** [comment]
Thanks so much. Of course.

Debugger entered--Lisp error: (wrong-number-of-arguments (3 . 4) 5)
  window--display-buffer(#<buffer *Ilist*> #<window 8 on test.fountain> window nil t)
  imenu-list-display-buffer(#<buffer *Ilist*> nil)
  display-buffer("*Ilist*")
  imenu-list-show-noselect()
  imenu-list-minor-mode(toggle)
  funcall-interactively(imenu-list-minor-mode toggle)
  call-interactively(imenu-list-minor-mode record nil)
  command-execute(imenu-list-minor-mode record)
  execute-extended-command(nil "imenu-list-minor-mode" "imenu-list-mino")
  funcall-interactively(execute-extended-command nil "imenu-list-minor-mode" "imenu-list-mino")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)

**Comment by bmag** [comment]
You are using an old version or a modified version of imenu-list. This bug was fixed two years ago, see https://github.com/bmag/imenu-list/commit/46008738f8fef578a763c308cf6695e5b4d4aa77.

**Comment by eldritchgreene** [comment]
Thanks so much for checking this! That's bizarre, the issue started when I switched devices and I just installed freshly from Melpa. Perhaps I have my package repositories mixed up. I will double check that now.

**Comment by bmag** [comment]
Perhaps you are using stable melpa? (https://stable.melpa.org/packages/) The version there indeed is old. I just tagged the latest version as a new release (v0.9), so the package on stable melpa should get updated soon (I hope automatically within several hours, but it's been a while since last time I checked their procedures).

**Comment by eldritchgreene** [comment]
That was exactly it! Fixed now thank you SO much.

**Comment by eldritchgreene** [comment]
That was exactly it! All fixed now. Thank you so much.
