### ISSUE TITLE
Require exception on Emacs 28.x

### ISSUE THREAD

**Issue by liny01-nbsa** [bmag/imenu-list#68]
<details>
  <summary>Details</summary>

  ```
Debugger entered--Lisp error: (wrong-number-of-arguments (3 . 4) 2)
  #f(compiled-function (obsolete-name current-name when &optional docstring) "Set OBSOLETE-NAME's function definition to CURRENT-NAME and mark it obsolete.\n\n(define-obsolete-function-alias \\='old-fun \\='new-fun \"22.1\" \"old-fun's doc.\")\n\nis equivalent to the following two lines of code:\n\n(defalias \\='old-fun \\='new-fun \"old-fun's doc.\")\n(make-obsolete \\='old-fun \\='new-fun \"22.1\")\n\nWHEN should be a string indicating when the function was first\nmade obsolete, for example a date or a release number.\n\nSee the docstrings of `defalias' and `make-obsolete' for more details." #<bytecode 0x15dffc687e09c5d0>)('imenu-list-update-safe 'imenu-list-update)
  (define-obsolete-function-alias 'imenu-list-update-safe 'imenu-list-update)
  load-with-code-conversion("/home/lin/emacs/spacemacs/elpa/28.0/develop/imenu-..." "/home/lin/emacs/spacemacs/elpa/28.0/develop/imenu-..." nil t)
  require(imenu-list)

  ```
</details>

And the offending line is below:

https://github.com/bmag/imenu-list/blob/b03b86aee6ac30067906dddc385db8188657d023/imenu-list.el#L695

Update the above code to

```elisp
(define-obsolete-function-alias 'imenu-list-update-safe 'imenu-list-update "Ver. X") 
```
fixes the issue.

This is first reported at syl20bnr/spacemacs#14565

**Comment by bmag** [comment]
Thanks for bringing this to my attention. Pushed a fix, should be available from Melpa shortly.

**Comment by yssource** [comment]
`pyright --version`

pyright 1.1.126

Error running timer ‘imenu-list-update’: (error "Timeout while waiting for response. Method: textDocument/documentSymbol.")

**Comment by bmag** [comment]
@yssource that's an unrelated issue. I expect you'll get the same error with just `M-x imenu` sometimes.

**Comment by yssource** [comment]
@bmag Thanks, a lot.

It works for me now, after updating to the latest imenu-list and emacs version.
