### ISSUE TITLE
[Feature Request] List all imenu entries in the project.

### ISSUE THREAD

**Issue by BooAA** [bmag/imenu-list#75]
It will be great if we can have a option to make `imenu-list` list all symbols in the current project (maybe grouped by their file name) so that we can have similar functionality to those project explorer (like treemacs) but much more simpler.

**Comment by bmag** [comment]
Hi @BooAA, thanks for the feedback. The scope of imenu-list is to show in a sidebar the index provided by imenu. Imenu itself is meant to provide only an index of the current buffer, although you could overwrite it with some effort. This means showing all symbols in a project is out of scope for imenu-list, sorry.
