### ISSUE TITLE
Fix imenu-list window width

### ISSUE THREAD

**Issue by tuhdo** [bmag/imenu-list#9]
Currently when activated, `imenu-list` shows the buffer in half. I think a user should be able to set according to percentage.

**Comment by bmag** [comment]
Good point. I intentionally didn't do anything fancy when showing `imenu-list`, so users can change it as they like via `display-buffer-alist` or `window-purpose`. However, I should probably change the default behavior. Expect I'll change it today or tomorrow.

**Comment by bmag** [comment]
Done
